### ISSUE TITLE
use arq instead of rq, using sqlalchemy-orm async version

### ISSUE THREAD

**Issue by malikovss** [uzbekvoice/UzbekVoiceBot#46]
Now rq is used for queueing tasks, there is an async version of this package.
If [arq](https://github.com/samuelcolvin/arq) is used instead of rq, on startup it will be possible to create one aiohttp session for all requests and use it anywhere and close it once its done. 

All sqlalchemy operations are written in sync version. I'm changing 'em to async. It's almost done.

**Comment by DavraYoung** [comment]
@malikovss hi, thank you for your contribution.

1. Rewrite code to use more of async with arq and sqlalchemy is a good idea, we look forward your PR.
2. I am not sure what benefits will sharing aiohttp give to us? Do you mean reusing same tcp connection?

Some context: 
it was done with rq to avoid waiting for the response, because server is sometimes responding slow (0.5-10 seconds) because of mariadb database on backend(we are currently optimizing database on server side).

**Comment by malikovss** [comment]
![IMG_20221125_095450_020](https://user-images.githubusercontent.com/47824375/203904209-91347c23-a775-416e-bfb2-240152ddb419.jpg)

https://docs.aiohttp.org/en/stable/http_request_lifecycle.html#using-a-session-as-a-best-practice
